# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae68a154aa990d374376b10500229547c5d72c46be5053043973502d73014858a14eb66131a4fb0e963dd460f334cec06c71b5b2f5b8464104b9e081961608ca

test:
  secret_key_base: 956d635228241c8e8cf84db6610ff78193e596326cc736ae80c4753be833278a649f639cdfffbb9f387d672f40ae8b4275c00ba20638c75887445b6f9e54145f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
